// <auto-generated />
using System;
using FarulewskiKlinika.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FarulewskiKlinika.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20191227183110_FirstMigration")]
    partial class FirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FarulewskiKlinika.Models.Pacjent", b =>
                {
                    b.Property<int>("PacjentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nazwisko")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pesel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PacjentID");

                    b.ToTable("Pacjenci");

                    b.HasData(
                        new
                        {
                            PacjentID = 1,
                            Email = "styczen@wp.pl",
                            Imie = "Konrad",
                            Nazwisko = "Styczen",
                            Pesel = "11111111111"
                        },
                        new
                        {
                            PacjentID = 2,
                            Email = "luty@wp.pl",
                            Imie = "Agata",
                            Nazwisko = "Luty",
                            Pesel = "22222222222"
                        },
                        new
                        {
                            PacjentID = 3,
                            Email = "marzec@wp.pl",
                            Imie = "Jan",
                            Nazwisko = "Marzec",
                            Pesel = "33333333333"
                        });
                });

            modelBuilder.Entity("FarulewskiKlinika.Models.Pracownik", b =>
                {
                    b.Property<int>("PracownikID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nazwisko")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rola")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Specjalizacja")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PracownikID");

                    b.ToTable("Pracownicy");
                });

            modelBuilder.Entity("FarulewskiKlinika.Models.Wizyta", b =>
                {
                    b.Property<int>("WizytaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataWizyty")
                        .HasColumnType("datetime2");

                    b.Property<int>("LekarzID")
                        .HasColumnType("int");

                    b.Property<int>("PacjentID")
                        .HasColumnType("int");

                    b.Property<string>("Specjalizacja")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Zalecenia")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("WizytaID");

                    b.HasIndex("LekarzID");

                    b.HasIndex("PacjentID");

                    b.ToTable("Wizyty");
                });

            modelBuilder.Entity("FarulewskiKlinika.Models.Wizyta", b =>
                {
                    b.HasOne("FarulewskiKlinika.Models.Pracownik", "Lekarz")
                        .WithMany("Wizyty")
                        .HasForeignKey("LekarzID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FarulewskiKlinika.Models.Pacjent", "Pacjent")
                        .WithMany("Wizyty")
                        .HasForeignKey("PacjentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
